[package]
name = "task_2_8"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "2.2.7"
solana-sdk = "2.2.2"
spl-token = "8.0.0"
spl-associated-token-account = "6.0.0"
dotenv = "0.15"
serde_json = "1.0"

mpl-token-metadata = "5.1.0"
